name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Extract ECR repository URI
        run: echo "REPOSITORY=${{ secrets.ECR_REPOSITORY }}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build -t my-medusa-app .
          docker tag my-medusa-app:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push the Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Verify Docker Image on ECR
        run: |
          aws ecr describe-images --repository-name my-medusa-app --image-ids imageTag=latest
