name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  # Or 'master', depending on your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Access key from GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Secret key from GitHub Secrets
          aws-region: us-east-1  # Hard-coded AWS region (replace with your region if different)

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Docker image
        run: |
          docker build -t medusa-app .
          docker tag medusa-app:latest ${{ secrets.ECR_REPOSITORY }}:latest  # Tag with ECR repo URI

      - name: Push the Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest  # Push to ECR
